language: objective-c
osx_image: xcode10.2
env: SWIFT_SNAPSHOT=5.0

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - DESTINATION="OS=12.0,name=iPhone XS"

before_install:
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --pre --no-document --quiet

script:
  - set -o pipefail
  - sh Startup.sh
  - pod lib lint --allow-warnings --verbose

after_success:
  - sleep 3
  